site_name: Big Data Aplicado
nav:
  - "Inicio": "index.md"
  - "UT1. Introducción a Big Data Aplicado y Hadoop":
      - "1. Motivación y Origen": "ut1-introduccion-a-hadoop/1motivacionyorigen.md"
      - "2. Apache Hadoop a Alto Nivel": 
          - "2.1. ¿Qué es Apache Hadoop?": "ut1-introduccion-a-hadoop/21queesapachehadoop.md"
          - "2.2. Ecosistema Hadoop y sus Distribuciones": "ut1-introduccion-a-hadoop/22ecosistemahadoopydistribuciones.md"
          - "2.3. Arquitectura": "ut1-introduccion-a-hadoop/23arquitectura.md"
      - "Prácticas y Tareas": "ut1-introduccion-a-hadoop/indicedetareas.md"
  - "UT2. Almacenamiento y Procesamiento en Hadoop":
      - "1. HDFS": "ut2-almacenamiento-y-procesamiento-en-hadoop/1hdfs.md"
      - "2. MapReduce": "ut2-almacenamiento-y-procesamiento-en-hadoop/2mapreduce.md"
      - "Prácticas y Tareas": "ut2-almacenamiento-y-procesamiento-en-hadoop/tareas/index.md"
  - "UT3. Ecosistema de Hadoop":
      - "1. Introducción al Ecosistema de Hadoop": "ut3-ecosistema-de-hadoop/1introduccion.md"
      - "2. Componentes de Acceso y Procesamiento": 
          - "2.1. Apache Pig": "ut3-ecosistema-hadoop/2componentes-acceso-procesamiento/21apache-pig.md"
      - "Prácticas y Tareas": "ut3-ecosistema-hadoop/tareas/index.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
plugins:
  - search:
      lang: es
  - glightbox

theme:
  name: material
  features:
    - navigation.footer
  palette:
    - scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Quitar modo oscuro
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-3VWRJDCQS9
    feedback:
      title: <a href='https://ko-fi.com/jgarciadeparedesh02' title='Invítame a un café en ko-fi.com' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=3' border='0' alt='Invítame a un café en ko-fi.com' /></a>
      ratings:
        - icon: material/emoticon-happy-outline
          name: Esta página es genial
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Podría mejorar
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.